# Generated by Django 2.2.14 on 2020-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ggtrfkuytkuytkuyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jytuytuyt', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customtext',
            name='daefqfcrqrfcqrefc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='jhfjhfjgfhgfjfgjhjkhg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
