# Generated by Django 2.2.14 on 2020-07-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200729_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='daefqfcrqrfcqrefc',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='jhfjhfjgfhgfjfgjhjkhg',
        ),
    ]
